name: ✨Feature Request
description: Request a new feature or enhancement
title: "[FEAT]: "
labels: ["Enhancement"]
assignees: ["DOS1986"]
body:
- type: markdown
  attributes:
    value: |
      Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues

- type: checkboxes
  id: search-existing-issues
  attributes:
    label: Searched existing issues.
    description: Please make sure this feature request hasn't already been submitted by someone by looking through other open/closed issues.
    options:
      - label: I have searched existing issues already.
        required: true
      - label: I have not searched any issues
        

- type: textarea
  id: description
  attributes:
    label: Description
    description: Give us a brief description of the feature or enhancement you would like
    value: |
      1.
      2. 
      3.
  validations:
    required: true

- type: textarea
  id: additional-information
  attributes:
    label: Additional Information
    description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.