name: 💭 Proposal
description: Suggest an idea for a specific feature you wish to propose to the community for comment
title: "[PROPOSAL]: "
labels: ["Proposal"]
assignees: ["DOS1986"]
body:
- type: markdown
  attributes:
    value: |
        ## What/Why
        ### What are you proposing?
        **In a few sentences, describe the feature and its core capabilities.**

- type: textarea
  id: who-asked-for-feature
  attributes:
    label: What users have asked for this feature?
    description: |
      Highlight any research, proposals, requests or anecdotes that signal this is the right thing to build. 
      Include links to GitHub Issues, Forums, Stack Overflow, Twitter, Etc
  validations:
    required: True

- type: textarea
  id: problem-to-solve
  attributes:
    label: What problems are you trying to solve?
    description: | 
      Summarize the core use cases and user problems and needs you are trying to solve. 
      Describe the most important user needs, pain points and jobs as expressed by the user asks above. 
      Template: When \<a situation arises> , a \<type of user> wants to \<do something>, so they can \<expected outcome>. 
      (Example: When **searching by postal code**, **a buyer** wants to **be required to enter a valid code**so they **don’t waste time searching for a clearly invalid postal code.**)
  validations:
    required: True

- type: textarea
  id: developer-experience
  attributes:
    label: What is the developer experience going to be?
    description: |
      Does this have a REST API? If so, please describe the API and any impact it may have to existing APIs. 
      In a brief summary (not a spec), highlight what new REST APIs or changes to REST APIs are planned. 
      as well as any other API, CLI or Configuration changes that are planned as part of this feature.
  validations:
    required: True

- type: textarea
  id: security-considerations
  attributes:
    label: Are there any security considerations?
    description: |
      Describe if the feature has any security considerations or impact.
      What is the security model of the new APIs? 
      Features should be integrated into the OpenSearch security suite and so if they are not, we should highlight the reasons here.
  validations:
    required: True

- type: textarea
  id: user-experience
  attributes:
    label: What is the user experience going to be?
    description: |
      Describe the feature requirements and or user stories. 
      You may include low-fidelity sketches, wireframes, APIs stubs, or other examples of how a user would use the feature via CLI. 
      OpenSearch Dashboards, REST API, etc. 
      Using a bulleted list or simple diagrams to outline features is okay. If this is net new functionality, call this out as well.
  validations:
    required: True

- type: textarea
  id: breaking-changes-to-user-experience
  attributes:
    label: Are there breaking changes to the User Experience?
    description: |
      Will this change the existing user experience? 
      Will this be a breaking change from a user flow or user experience perspective?
  validations:
    required: True

- type: textarea
  id: reason-to-build
  attributes:
    label: Why should it be built? Any reason not to?
    description: |
      Describe the value that this feature will bring to the OpenSearch community, as well as what impact it has if it isn't built, or new risks if it is. 
      Highlight opportunities for additional research.
  validations:
    required: True

- type: textarea
  id: take-to-execute
  attributes:
    label: What will it take to execute?
    description: | 
      Describe what it will take to build this feature. 
      Are there any assumptions you may be making that could limit scope or add limitations? 
      Are there performance, cost, or technical constraints that may impact the user experience? 
      Does this feature depend on other feature work? What additional risks are there?
  validations:
    required: True

- type: textarea
  id: open-questions
  attributes:
    label: Any remaining open questions?
    description: |
      What are known enhancements to this feature? 
      Any enhancements that may be out of scope but that we will want to track long term? 
      List any other open questions that may need to be answered before proceeding with an implementation.
  validations:
    required: True