name: Add triaged bugs & tasks to project board
# https://github.com/actions/add-to-project

on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://https://github.com/orgs/ecpkeeper/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: Issue-Feature, Needs-Triage, Needs-Author-Feedback, Issue-Scenario
          label-operator: NOT
